[package]
name = "carrel-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
build = "build.rs"

[lib]
name = "carrel_app"
path = "src/lib.rs"

[dependencies]
cozo = { workspace = true }
carrel-store = { workspace = true }
serde = { workspace = true }
tauri = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }
