[package]
name = "carrel-app-frontend"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "carrel-app-frontend"
path = "src/main.rs"

[features]
default = ["ssr"]
csr = [
    "dep:serde-wasm-bindgen",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    "dep:web-sys",
    "leptos/csr",
]
ssr = ["leptos/ssr", "leptos_router/ssr"]

[dependencies]
carrel-core = { path = "../../carrel-core", default-features = false }
leptos = { workspace = true }
leptos_router = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }
